osx_image: xcode12
os: osx
language: swift

env:
  - DESTINATION='platform=iOS Simulator,name=iPhone 6,OS=12.4'
  - DESTINATION='platform=iOS Simulator,name=iPhone 8,OS=13.5'
  - DESTINATION='platform=iOS Simulator,name=iPhone 11 Pro,OS=14.0'

script:
  - swift package update && xcodebuild test -scheme OKImageDownloaderTests -destination "$DESTINATION"
