osx_image: xcode12
os: osx
language: swift

env:
  - DESTINATION='platform=iOS Simulator,name=iPhone X,OS=12.0'
  - DESTINATION='platform=iOS Simulator,name=iPhone Xs,OS=13.0'
  - DESTINATION='platform=iOS Simulator,name=iPhone 11 Pro,OS=14.0'
  - PROJECT_NAME='OKImageDownloader/'

install: (cd $PROJECT_NAME && swift package update)
script:
  - (cd $PROJECT_NAME && xcodebuild test -scheme OKImageDownloader -destination $DESTINATION)